### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by 0999312** [0999312/Gensokyo-Story#1]
- [ ] Better Code 代码调整/冗余代码清理    高优先级
- [ ] Farming with Day/Night cycle 依赖目前日夜循环系统的种植系统    高优先级
- [ ] Item 物品的实现    高优先级
- [ ] ItemBuilding 可建造物的实现    高优先级
- [ ] PlayerInventory 玩家物品栏    高优先级
- [ ] Player Stats 玩家各种数值状态    高优先级
- [ ] Multi Player 多人游戏    高优先级/长期
- [ ] Save/Load 保存/加载    高优先级
- [ ] GUI Remake 重做GUI
- [ ] Player character setting 玩家角色设置界面/玩家换色
- [ ] Weather 天气
- [ ] Trees 树木/伐木
- [ ] Animals 动物/养殖
- [ ] MORE Numbers 我们需要更多的参与人员    长期
- [ ] MORE Textures 我们需要更多的材质    长期
